- name: restart nginx
  command: /bin/true
  notify:
  - test nginx configuration
  - restart nginx - after config test

- name: reload nginx
  command: /bin/true
  notify:
  - test nginx configuration
  - reload nginx - after config test

- name: test nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  register: nginx_test
  changed_when: nginx_test.rc != 0

- name: restart nginx - after config test
  service:
    name: nginx
    state: restarted

- name: reload nginx - after config test
  service:
    name: nginx
    state: reloaded